spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_marketplace
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true

  main:
    banner-mode: off
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: 4eb21ffda60106
    password: bcde514f554e0d

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

